//! Snapshot runtime scaffolding for userfaultfd-driven CoW paging.
//!
//! This module is intentionally Linux-agnostic at the syscall boundary so it
//! remains unit-testable on any host. It provides:
//!
//! - userfaultfd protocol constants used during feature negotiation;
//! - a normalized page-fault event type;
//! - a small CoW pager state machine that resolves a faulting guest address to
//!   the backing-file byte range that should be copied into guest RAM.
//!
//! The actual `userfaultfd(2)` file descriptor lifecycle (`UFFDIO_API`,
//! `UFFDIO_REGISTER`, `UFFDIO_COPY`, polling) is wired in a later Linux-only
//! integration step.

use thiserror::Error;

use crate::{BackingFileHeader, BACKING_HDR_LEN};

/// `UFFD_API` value used by `UFFDIO_API` negotiation (`linux/userfaultfd.h`).
pub const UFFD_API: u64 = 0xAA;

/// `UFFDIO_REGISTER_MODE_MISSING` bit for "missing page" fault tracking.
pub const UFFDIO_REGISTER_MODE_MISSING: u64 = 1 << 0;

/// `UFFD_PAGEFAULT_FLAG_WRITE` bit for write faults in page-fault events.
pub const UFFD_PAGEFAULT_FLAG_WRITE: u64 = 1 << 0;

/// Normalized userfaultfd page-fault event data.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct UffdPagefaultEvent {
    /// Faulting guest virtual address.
    pub address: u64,
    /// Raw userfaultfd page-fault flags.
    pub flags: u64,
}

impl UffdPagefaultEvent {
    /// Construct a new page-fault event.
    pub fn new(address: u64, flags: u64) -> Self {
        Self { address, flags }
    }

    /// `true` if the event was generated by a write access.
    pub fn is_write(&self) -> bool {
        self.flags & UFFD_PAGEFAULT_FLAG_WRITE != 0
    }
}

/// Decision returned by [`CowPager::handle_fault`].
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CowFaultAction {
    /// Page is missing and should be copied from backing storage.
    PopulateFromBacking {
        /// 0-based page number inside the snapshot memory image.
        page_index: u64,
        /// Guest page-aligned address for the target mapping.
        guest_page_addr: u64,
        /// Byte offset inside `memory.cow` where the source page starts.
        backing_offset: u64,
        /// Number of bytes to copy (`page_size`).
        len: u32,
    },
    /// Page is already resident; no copy is needed.
    AlreadyMapped {
        /// 0-based page number inside the snapshot memory image.
        page_index: u64,
        /// Guest page-aligned address for the resolved page.
        guest_page_addr: u64,
    },
}

/// Errors returned by CoW runtime helpers.
#[derive(Debug, Clone, Error, PartialEq, Eq)]
#[non_exhaustive]
pub enum RuntimeError {
    /// Guest base address is not page aligned.
    #[error("guest base address 0x{base_addr:016x} is not aligned to page size {page_size}")]
    MisalignedBase {
        /// Guest memory base address.
        base_addr: u64,
        /// Snapshot page size.
        page_size: u32,
    },
    /// Fault address is outside the tracked guest memory range.
    #[error(
        "fault address 0x{fault_addr:016x} out of range [0x{base_addr:016x}, 0x{end_addr:016x})"
    )]
    FaultOutOfRange {
        /// Faulting address.
        fault_addr: u64,
        /// Inclusive start of tracked memory.
        base_addr: u64,
        /// Exclusive end of tracked memory.
        end_addr: u64,
    },
    /// Page count cannot fit in host `usize` for resident bitmap allocation.
    #[error("snapshot page_count {page_count} does not fit in host usize")]
    PageCountTooLarge {
        /// Snapshot page count from the backing header.
        page_count: u64,
    },
    /// Arithmetic overflow while computing page addresses or offsets.
    #[error("overflow while computing CoW fault resolution")]
    ArithmeticOverflow,
}

/// CoW page-fault resolver over a snapshot backing file geometry.
#[derive(Debug, Clone)]
pub struct CowPager {
    base_addr: u64,
    page_size: u32,
    page_count: u64,
    resident: Vec<bool>,
}

impl CowPager {
    /// Build a pager from guest memory base + snapshot backing geometry.
    pub fn new(base_addr: u64, backing: BackingFileHeader) -> Result<Self, RuntimeError> {
        if !base_addr.is_multiple_of(backing.page_size as u64) {
            return Err(RuntimeError::MisalignedBase {
                base_addr,
                page_size: backing.page_size,
            });
        }
        let resident_len: usize = backing
            .page_count
            .try_into()
            .map_err(|_| RuntimeError::PageCountTooLarge {
                page_count: backing.page_count,
            })?;
        Ok(Self {
            base_addr,
            page_size: backing.page_size,
            page_count: backing.page_count,
            resident: vec![false; resident_len],
        })
    }

    /// Handle a normalized page-fault event.
    pub fn handle_event(
        &mut self,
        event: UffdPagefaultEvent,
    ) -> Result<CowFaultAction, RuntimeError> {
        self.handle_fault(event.address)
    }

    /// Resolve a faulting address to a CoW action.
    pub fn handle_fault(&mut self, fault_addr: u64) -> Result<CowFaultAction, RuntimeError> {
        let total = self
            .page_count
            .checked_mul(self.page_size as u64)
            .ok_or(RuntimeError::ArithmeticOverflow)?;
        let end_addr = self
            .base_addr
            .checked_add(total)
            .ok_or(RuntimeError::ArithmeticOverflow)?;
        if fault_addr < self.base_addr || fault_addr >= end_addr {
            return Err(RuntimeError::FaultOutOfRange {
                fault_addr,
                base_addr: self.base_addr,
                end_addr,
            });
        }

        let rel = fault_addr
            .checked_sub(self.base_addr)
            .ok_or(RuntimeError::ArithmeticOverflow)?;
        let page_size_u64 = self.page_size as u64;
        let page_index = rel / page_size_u64;
        let guest_page_addr = self
            .base_addr
            .checked_add(page_index * page_size_u64)
            .ok_or(RuntimeError::ArithmeticOverflow)?;
        let idx: usize = page_index
            .try_into()
            .map_err(|_| RuntimeError::PageCountTooLarge {
                page_count: self.page_count,
            })?;
        if self.resident[idx] {
            return Ok(CowFaultAction::AlreadyMapped {
                page_index,
                guest_page_addr,
            });
        }
        self.resident[idx] = true;

        let data_offset = page_index
            .checked_mul(page_size_u64)
            .ok_or(RuntimeError::ArithmeticOverflow)?;
        let backing_offset = (BACKING_HDR_LEN as u64)
            .checked_add(data_offset)
            .ok_or(RuntimeError::ArithmeticOverflow)?;
        Ok(CowFaultAction::PopulateFromBacking {
            page_index,
            guest_page_addr,
            backing_offset,
            len: self.page_size,
        })
    }

    /// Number of pages already marked resident by prior faults.
    pub fn resident_pages(&self) -> usize {
        self.resident.iter().filter(|&&b| b).count()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_backing() -> BackingFileHeader {
        BackingFileHeader::new(4096, 4).expect("valid geometry")
    }

    #[test]
    fn write_flag_helper_is_bit_exact() {
        let read = UffdPagefaultEvent::new(0x1000, 0);
        let write = UffdPagefaultEvent::new(0x1000, UFFD_PAGEFAULT_FLAG_WRITE);
        assert!(!read.is_write());
        assert!(write.is_write());
    }

    #[test]
    fn pager_rejects_misaligned_base() {
        let err = CowPager::new(0x1001, sample_backing()).unwrap_err();
        assert!(matches!(
            err,
            RuntimeError::MisalignedBase {
                base_addr: 0x1001,
                page_size: 4096
            }
        ));
    }

    #[test]
    fn first_fault_populates_and_second_fault_is_already_mapped() {
        let mut pager = CowPager::new(0x4000_0000, sample_backing()).unwrap();
        let first = pager.handle_fault(0x4000_1234).unwrap();
        assert_eq!(
            first,
            CowFaultAction::PopulateFromBacking {
                page_index: 1,
                guest_page_addr: 0x4000_1000,
                backing_offset: BACKING_HDR_LEN as u64 + 4096,
                len: 4096,
            }
        );

        let second = pager.handle_fault(0x4000_1abc).unwrap();
        assert_eq!(
            second,
            CowFaultAction::AlreadyMapped {
                page_index: 1,
                guest_page_addr: 0x4000_1000
            }
        );
        assert_eq!(pager.resident_pages(), 1);
    }

    #[test]
    fn handle_event_uses_event_address() {
        let mut pager = CowPager::new(0x8000_0000, sample_backing()).unwrap();
        let ev = UffdPagefaultEvent::new(0x8000_0008, UFFD_PAGEFAULT_FLAG_WRITE);
        let action = pager.handle_event(ev).unwrap();
        assert_eq!(
            action,
            CowFaultAction::PopulateFromBacking {
                page_index: 0,
                guest_page_addr: 0x8000_0000,
                backing_offset: BACKING_HDR_LEN as u64,
                len: 4096,
            }
        );
    }

    #[test]
    fn out_of_range_fault_is_rejected() {
        let mut pager = CowPager::new(0x1000_0000, sample_backing()).unwrap();
        let err = pager.handle_fault(0x0fff_ffff).unwrap_err();
        assert!(matches!(
            err,
            RuntimeError::FaultOutOfRange {
                fault_addr: 0x0fff_ffff,
                ..
            }
        ));
    }
}
