#!/usr/bin/env bash
#
# One-command Fly.io bring-up for the live-KVM demo.
#
# Usage:
#   ./deploy.sh                 # uses app name "nanovm-live-demo"
#   NANOVM_LIVE_DEMO_APP=my-demo ./deploy.sh
#
# Writes fresh per-org tokens to `../.env.local` (gitignored) so
# `load.sh` and `tail.sh` can source them without you copy-pasting.

set -euo pipefail

APP="${NANOVM_LIVE_DEMO_APP:-nanovm-live-demo}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "$HERE/.." && pwd)"
ENV_FILE="$ROOT/.env.local"

log() { printf '\033[36m➜\033[0m %s\n' "$*"; }
die() { printf '\033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

command -v flyctl >/dev/null 2>&1 \
  || die "flyctl not on PATH. Install: https://fly.io/docs/hands-on/install-flyctl/"

flyctl auth whoami >/dev/null 2>&1 \
  || die "flyctl not logged in. Run: flyctl auth login"

# ---- Create app if missing ------------------------------------------
if ! flyctl apps show --app "$APP" >/dev/null 2>&1; then
  log "creating Fly app: $APP"
  flyctl apps create --name "$APP" --org personal
else
  log "reusing existing Fly app: $APP"
fi

# ---- Generate + persist tokens --------------------------------------
gen_token() {
  # openssl is the fast path; POSIX `od` is the fallback (xxd isn't
  # POSIX and Alpine/BusyBox hosts don't have it).
  openssl rand -hex 24 2>/dev/null \
    || od -An -tx1 -N24 /dev/urandom | tr -d ' \n'
}

if [[ ! -f "$ENV_FILE" ]]; then
  log "generating fresh per-org tokens → $ENV_FILE"
  ACME_TOK="$(gen_token)"
  GLOBEX_TOK="$(gen_token)"
  INITECH_TOK="$(gen_token)"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh — do not commit. Regenerate by deleting this
# file and re-running deploy.sh, then \`flyctl secrets set\` will push
# the new set to the running app.
NANOVM_LIVE_DEMO_APP=$APP
NANOVM_LIVE_DEMO_HOST=$APP.fly.dev
NANOVM_LIVE_DEMO_BASE_URL=https://$APP.fly.dev
ACME_TOKEN=$ACME_TOK
GLOBEX_TOKEN=$GLOBEX_TOK
INITECH_TOKEN=$INITECH_TOK
EOF
else
  log "reusing existing tokens from $ENV_FILE"
fi
# shellcheck disable=SC1090
source "$ENV_FILE"

# ---- Push tokens as Fly secrets -------------------------------------
log "planting NANOVM_API_TOKENS as Fly secret"
flyctl secrets set --app "$APP" --stage \
  NANOVM_API_TOKENS="acme:$ACME_TOKEN,globex:$GLOBEX_TOKEN,initech:$INITECH_TOKEN" \
  >/dev/null

# ---- Deploy ---------------------------------------------------------
log "deploying (image pulled from ghcr.io/ip888/nanovm-control-plane-kvm:latest)"
flyctl deploy --app "$APP" --config "$HERE/fly.toml" --ha=false

# ---- Verify /dev/kvm actually landed --------------------------------
log "verifying backend self-reports as kvm"
BACKEND="$(curl -fsS "https://$APP.fly.dev/v1/health" \
  -H "Authorization: Bearer $ACME_TOKEN" \
  | grep -o '"backend":"[^"]*"' | cut -d'"' -f4 || echo unknown)"
if [[ "$BACKEND" != "kvm" ]]; then
  die "backend reports \"$BACKEND\" — /dev/kvm probably isn't exposed. Check that the Fly machine landed on a performance-CPU host in a KVM-capable region."
fi

log "live-KVM control plane is up:"
printf '   %s\n' "https://$APP.fly.dev/v1/health"
printf '   %s\n' "https://$APP.fly.dev/metrics"
printf '\nNext:\n'
printf '   \033[33mcd %s && ./up.sh\033[0m   # spin up local Prometheus + Grafana pointed here\n' "$ROOT"
