{{/* Tokens secret. Operators wanting external secret management
     should `--set config.apiTokens=` and create their own secret
     with the same key. */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nanovm.fullname" . }}-tokens
  labels:
    {{- include "nanovm.labels" . | nindent 4 }}
type: Opaque
stringData:
  NANOVM_API_TOKENS: {{ .Values.config.apiTokens | quote }}
