#!/usr/bin/env bash
#
# Bring the live-KVM demo up entirely on your local Linux + KVM box.
# No cloud, no accounts, no cost. Runs 4 docker containers:
#
#   1. nanovm-control-plane-kvm — the REAL binary, /dev/kvm mapped in
#   2. Prometheus                — scraping (1) at 15 s
#   3. Grafana                   — same dashboard as the Fly.io demo
#   4. (no fourth — load.sh + tail-local.sh run on the host)
#
# Requires:
#   - Linux host with /dev/kvm (Intel `vmx` or AMD `svm`)
#   - docker + docker compose
#   - curl, openssl (or /dev/urandom)
#
# For M1 / macOS / Windows, use ./up.sh instead (Fly.io path).

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

log()  { printf '\033[36m➜\033[0m %s\n' "$*"; }
warn() { printf '\033[33m!\033[0m %s\n' "$*"; }
die()  { printf '\033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

# ---- Preflight: real KVM available? ---------------------------------
log "checking /dev/kvm on this host"
[[ -c /dev/kvm ]] \
  || die "/dev/kvm not present. Install KVM: 'sudo pacman -S qemu-full' (Arch/Omarchy) or 'sudo apt install qemu-kvm' (Debian/Ubuntu), then reboot / modprobe kvm-intel or kvm-amd."

if ! command -v docker >/dev/null 2>&1; then
  die "docker not on PATH"
fi
if ! docker compose version >/dev/null 2>&1; then
  die "docker compose plugin not installed"
fi

# ---- Discover the host's `kvm` group GID so the container can open /dev/kvm.
#      Debian family uses 36, RHEL/Fedora uses 78, Arch/Omarchy varies.
KVM_GID="$(stat -c '%g' /dev/kvm)"
log "host /dev/kvm belongs to gid $KVM_GID (kvm group)"

# ---- Generate fresh per-org tokens ----------------------------------
ENV_FILE="$HERE/.env.local"
if [[ ! -f "$ENV_FILE" ]]; then
  gen_token() { openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | xxd -p; }
  ACME_TOKEN="$(gen_token)"
  GLOBEX_TOKEN="$(gen_token)"
  INITECH_TOKEN="$(gen_token)"
  log "minted fresh per-org tokens → $ENV_FILE"
  cat > "$ENV_FILE" <<EOF
# Generated by up-local.sh. Do not commit.
NANOVM_LIVE_DEMO_MODE=local
NANOVM_LIVE_DEMO_BASE_URL=http://localhost:8080
ACME_TOKEN=$ACME_TOKEN
GLOBEX_TOKEN=$GLOBEX_TOKEN
INITECH_TOKEN=$INITECH_TOKEN
EOF
else
  log "reusing existing tokens from $ENV_FILE"
fi
# shellcheck disable=SC1091
source "$ENV_FILE"
export KVM_GID
export NANOVM_API_TOKENS="acme:$ACME_TOKEN,globex:$GLOBEX_TOKEN,initech:$INITECH_TOKEN"

# ---- Pull the KVM image once so the first `up` isn't dominated by network.
log "pulling nanovm-control-plane-kvm:latest (if missing)"
docker pull ghcr.io/ip888/nanovm-control-plane-kvm:latest >/dev/null

# ---- Bring the stack up ---------------------------------------------
log "starting control-plane + Prometheus + Grafana (docker compose)"
docker compose -f ./compose/docker-compose.local.yml up -d

# ---- Wait for the control-plane to respond --------------------------
log "waiting for control-plane /healthz"
for i in {1..30}; do
  if curl -fsS http://localhost:8080/healthz >/dev/null 2>&1; then
    break
  fi
  sleep 1
  [[ $i -eq 30 ]] && die "control-plane didn't become healthy in 30 s. Check: docker logs nanovm-demo-control-plane"
done

# ---- Verify backend really says kvm ---------------------------------
log "verifying backend self-reports as kvm"
BACKEND="$(curl -fsS http://localhost:8080/v1/health \
  -H "Authorization: Bearer $ACME_TOKEN" \
  | grep -o '"backend":"[^"]*"' | cut -d'"' -f4 || echo unknown)"
if [[ "$BACKEND" != "kvm" ]]; then
  warn "backend reports \"$BACKEND\" — expected \"kvm\". /dev/kvm may not be usable inside the container despite being present on the host."
  warn "check:  docker exec nanovm-demo-control-plane ls -l /dev/kvm"
fi

cat <<EOF

\033[32m✓\033[0m Local live-KVM demo is running.

  \033[1mControl plane (real KVM on THIS host):\033[0m
    Health:    http://localhost:8080/v1/health   (backend: $BACKEND)
    Metrics:   http://localhost:8080/metrics
    OpenAPI:   http://localhost:8080/openapi.json

  \033[1mObservability:\033[0m
    Prometheus: http://localhost:9090
    Grafana:    http://localhost:3000/d/nanovm-overview

  \033[1mNext:\033[0m
    ./load.sh          # multi-org traffic generator — works for both local + Fly
    ./tail-local.sh    # streams docker logs + audit JSONL

  Then open http://localhost:3000/d/nanovm-overview and watch the panels
  move in real time. Every fork is a real KVM ioctl on your host kernel.

  \033[1mWhen done:\033[0m
    ./down-local.sh

EOF
